services:
  analytics:
    image: analytics:latest
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      TZ: Europe/Stockholm
      APP_NAME: Analytics
      SITE_DOMAIN: http://localhost:8080
    volumes:
      - ./data:/app/data
